services:
  - type: web
    name: ytcatbox
    runtime: docker
    plan: free
    envVars:
      - key: ACCESS_TOKEN
        sync: false
      - key: MAX_MB
        value: "1000"
      - key: TAILSCALE_AUTHKEY
        sync: false
      - key: PROXY
        sync: false
